### ISSUE TITLE
Auto Upload Rom

### ISSUE THREAD

**Issue by angelinemeenutech** [tyfkda/nesemu#14]
Is it Any possible to load rom automatically

**Comment by tyfkda** [comment]
@angelinemeenutech I think loading local file automatically is not allowed on browser.

**Comment by angelinemeenutech** [comment]
No tyfkda Am asking about preload rom For ex roms/supermario.nes - like this

**Comment by tyfkda** [comment]
@angelinemeenutech I don't have any plan to do so.
