### ISSUE TITLE
how to implement mapper033

### ISSUE THREAD

**Issue by citee520** [tyfkda/nesemu#32]
I have try implement mapper033 follow https://www.nesdev.org/wiki/INES_Mapper_033, PrgBank looke like has no problem, but CHRbank fail because photo is break, does someone can to help me how to write chrbank problem

**Comment by tyfkda** [comment]
@citee520 I haven't tried implementing mapper 33 yet, so I don't have any knowledge about it,
but it seems that Mesen supports it.

https://github.com/SourMesen/Mesen/blob/86326e832974d984846ae078e568c023a5f76f1f/Core/MapperFactory.cpp#L345
https://github.com/SourMesen/Mesen/blob/master/Core/TaitoTc0190.h

**Comment by citee520** [comment]
@tyfkda
thanks your help, I will try it, once successful, I will share to you.

**Comment by citee520** [comment]
@tyfkda 
Good news, I have implementing mapper 033, source code share to below link:
https://drive.google.com/drive/folders/1iASwQOLTQJCENFczEQagKQe6ms8TJrOl?usp=sharing
Thanks your help again.

**Comment by tyfkda** [comment]
@citee520 If you don't mind, could you send me a pull request?

**Comment by citee520** [comment]
@tyfkda
OK, I will try pull request.
If you have any problem please tell me.
Thanks.

**Comment by citee520** [comment]
I have pull request to you, pls check it's worded or not.
