### ISSUE TITLE
about mapper065 irq

### ISSUE THREAD

**Issue by citee520** [tyfkda/nesemu#36]
I want to implement mapper65,
follow as link to implement it, found some game can't run, some game break photo,
I think the problem is related to the interrupter,
I have no idea how to implement function "ProcessCpuClock", 
do you have any idea??
https://github.com/SourMesen/Mesen/blob/master/Core/IremH3001.h

**Comment by tyfkda** [comment]
@citee520 This emulator code doesn't have a method on a mapper to handle CPU cycles.
What you have available is an `onHblnak` method that is called every horizontal blanking interval.

**Comment by citee520** [comment]
OK, I will try your way to implement IRQ function.
